# Generated by Django 5.1.6 on 2025-03-10 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(255, 'the field must contain at least 250 characters')]),
        ),
    ]
