# Generated by Django 5.1.6 on 2025-03-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_alter_profile_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
